// <auto-generated />
namespace iCantine.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
<<<<<<<< Updated upstream:Migrations/202405312009227_update.Designer.cs
    public sealed partial class update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update));
        
        string IMigrationMetadata.Id
        {
            get { return "202405312009227_update"; }
========
    public sealed partial class InitialMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202405312152420_InitialMigration"; }
>>>>>>>> Stashed changes:Migrations/202405312152420_InitialMigration.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
