// <auto-generated />
namespace iCantine.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
<<<<<<< HEAD
<<<<<<<< HEAD:Migrations/202406151759376_InitialUpdate2.Designer.cs
=======
<<<<<<<< HEAD:Migrations/202406161624133_InitialUpdate6.Designer.cs
>>>>>>> ReceiptController
<<<<<<<< HEAD:Migrations/202406161624133_InitialUpdate6.Designer.cs
    public sealed partial class InitialUpdate6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialUpdate6));
        
        string IMigrationMetadata.Id
        {
            get { return "202406161624133_InitialUpdate6"; }
========
    public sealed partial class InitialUpdate2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialUpdate2));
        
        string IMigrationMetadata.Id
        {
            get { return "202406151759376_InitialUpdate2"; }
>>>>>>>> f8dc36c (Relações extras):Migrations/202406151759376_InitialUpdate2.Designer.cs
========
    public sealed partial class updt5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updt5));
        
        string IMigrationMetadata.Id
        {
            get { return "202406152310441_updt5"; }
<<<<<<< HEAD
>>>>>>>> a66022f (Funcoes principais para a criacao de recibos):Migrations/202406152310441_updt5.Designer.cs
=======
>>>>>>>> ReceiptController:Migrations/202406152310441_updt5.Designer.cs
>>>>>>> ReceiptController
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
