// <auto-generated />
namespace iCantine.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
<<<<<<<< HEAD:Migrations/202406151728331_update6.Designer.cs
    public sealed partial class update6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update6));
        
        string IMigrationMetadata.Id
        {
            get { return "202406151728331_update6"; }
========
    public sealed partial class InitialUpdate2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialUpdate2));
        
        string IMigrationMetadata.Id
        {
            get { return "202406151759376_InitialUpdate2"; }
>>>>>>>> f8dc36c (Relações extras):Migrations/202406151759376_InitialUpdate2.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
