// <auto-generated />
namespace iCantine.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
<<<<<<<< Updated upstream:Migrations/202406161737549_updt7.Designer.cs
    public sealed partial class updt7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updt7));
        
        string IMigrationMetadata.Id
        {
            get { return "202406161737549_updt7"; }
========
    public sealed partial class InitialUpdate9 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialUpdate9));
        
        string IMigrationMetadata.Id
        {
            get { return "202406170147362_InitialUpdate9"; }
>>>>>>>> Stashed changes:Migrations/202406170147362_InitialUpdate9.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
